# Generated by Django 5.0.6 on 2026-09-03 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('pipeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('factura', 'Factura'), ('nota_credito', 'Nota de Crédito')], default='factura', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviado a SIFEN'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], default='draft', max_length=20)),
                ('cdc', models.CharField(blank=True, max_length=44, null=True, unique=True)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('xml_content', models.TextField(blank=True)),
                ('kude_url', models.URLField(blank=True)),
                ('amount_subtotal', models.DecimalField(decimal_places=0, max_digits=15)),
                ('iva_5', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('iva_10', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('amount_total', models.DecimalField(decimal_places=0, max_digits=15)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('sifen_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clients.client')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='pipeline.deal')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-created_at'],
            },
        ),
    ]
