# Generated by Django 5.0.6 on 2026-05-31 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('capacitacion', 'Capacitación'), ('coaching', 'Coaching'), ('consultoria', 'Consultoría'), ('conferencia', 'Conferencia'), ('outdoor', 'Outdoor'), ('webinar', 'Webinar'), ('programa', 'Programa Integral'), ('otro', 'Otro')], max_length=30)),
                ('phase', models.CharField(choices=[('nueva', 'Nueva Negociación'), ('diagnostico', 'Diagnóstico'), ('propuesta', 'Envío de Propuesta'), ('replanteo', 'Replanteo / Ajustes'), ('perdida', 'Negociación Perdida'), ('ganada', 'Negociación Ganada')], default='nueva', max_length=20)),
                ('probability', models.IntegerField(default=10)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('estimated_close_date', models.DateField(blank=True, null=True)),
                ('actual_close_date', models.DateField(blank=True, null=True)),
                ('next_followup', models.DateField(blank=True, null=True)),
                ('last_followup', models.DateField(blank=True, null=True)),
                ('initial_need', models.TextField(blank=True)),
                ('diagnosis_notes', models.TextField(blank=True)),
                ('proposal_link', models.URLField(blank=True)),
                ('proposal_ppt_link', models.URLField(blank=True)),
                ('replan_reason', models.CharField(blank=True, max_length=30)),
                ('replan_notes', models.TextField(blank=True)),
                ('loss_reason', models.CharField(blank=True, choices=[('precio', 'Precio'), ('sin_presupuesto', 'Sin presupuesto'), ('competencia', 'Competencia'), ('falta_seguimiento', 'Falta de seguimiento'), ('cancelacion', 'Cancelación del proyecto'), ('no_prioridad', 'No era prioridad'), ('tiempo', 'Tiempo'), ('no_respondio', 'No respondió'), ('otro', 'Otro')], max_length=30)),
                ('loss_notes', models.TextField(blank=True)),
                ('reactivation_date', models.DateField(blank=True, null=True)),
                ('next_step', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Negociación',
                'verbose_name_plural': 'Negociaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhaseTransitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_phase', models.CharField(max_length=20)),
                ('to_phase', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_logs', to='pipeline.deal')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
