# Generated by Django 5.0.6 on 2026-06-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='amount_original',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='document_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
    ]
