# Generated by Django 5.0.6 on 2026-09-03 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('clients', '0002_add_document_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('detalle_servicio', models.TextField()),
                ('monto', models.DecimalField(decimal_places=0, max_digits=15)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_cobro', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('facturado', 'Facturado'), ('pendiente', 'Pendiente'), ('cobrado', 'Cobrado')], default='facturado', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
