# Generated by Django 5.0.6 on 2026-09-23 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('facturado', 'Facturado'), ('pendiente', 'Pendiente'), ('parcial', 'Pago parcial'), ('cobrado', 'Cobrado')], default='facturado', max_length=20),
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('categoria', models.CharField(choices=[('proveedor', 'Proveedor'), ('servicio', 'Servicio'), ('salario', 'Salario'), ('impuesto', 'Impuesto'), ('alquiler', 'Alquiler'), ('marketing', 'Marketing'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=15)),
                ('fecha', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Pago parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PagoEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=15)),
                ('fecha', models.DateField()),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta')], default='transferencia', max_length=20)),
                ('notas', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('egreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='billing.egreso')),
            ],
            options={
                'verbose_name': 'Pago de egreso',
                'verbose_name_plural': 'Pagos de egresos',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=15)),
                ('fecha', models.DateField()),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta')], default='transferencia', max_length=20)),
                ('notas', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='billing.factura')),
            ],
            options={
                'verbose_name': 'Pago de factura',
                'verbose_name_plural': 'Pagos de facturas',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
