# Generated by Django 5.0.6 on 2026-05-31 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('empresa', 'Empresa'), ('persona', 'Persona Física')], max_length=20)),
                ('status', models.CharField(choices=[('prospecto', 'Prospecto'), ('nuevo', 'Nuevo'), ('recurrente', 'Recurrente'), ('partner', 'Partner'), ('inactivo', 'Inactivo')], default='prospecto', max_length=20)),
                ('company_name', models.CharField(max_length=200)),
                ('ruc', models.CharField(blank=True, max_length=20)),
                ('ci', models.CharField(blank=True, max_length=20)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_position', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, choices=[('asuncion', 'Asunción'), ('alto_parana', 'Alto Paraná'), ('central', 'Central'), ('itapua', 'Itapúa'), ('amambay', 'Amambay'), ('caaguazu', 'Caaguazú'), ('cordillera', 'Cordillera'), ('guaira', 'Guairá'), ('paraguari', 'Paraguarí'), ('misiones', 'Misiones'), ('neembucu', 'Ñeembucú'), ('concepcion', 'Concepción'), ('san_pedro', 'San Pedro'), ('canindeyu', 'Canindeyú'), ('presidente_hayes', 'Presidente Hayes'), ('alto_paraguay', 'Alto Paraguay'), ('boqueron', 'Boquerón')], max_length=50)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('referido', 'Referido'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('networking', 'Networking'), ('webinar', 'Webinar'), ('cliente_actual', 'Cliente actual'), ('cold_call', 'Cold Call'), ('evento', 'Evento'), ('pagina_web', 'Página Web'), ('otro', 'Otro')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
    ]
