# Generated by Django 5.0.6 on 2026-06-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='document_link',
            field=models.URLField(blank=True),
        ),
    ]
